version: "3.8"

services:
  app:
    build: .
    # restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - .:/app
    command: sh -c "cd control-gastos-react && npm install && npm run dev"
    #command: sh -c "tail -F something"
